### ISSUE TITLE
gl1_pointparameters "1" doesn't make the particles square

### ISSUE THREAD

**Issue by drogga** [yquake2/yquake2#374]
Description is in the title.
My specs:
CPU: i7-4790K
GPU: NVidia GTX 970
RAM: 16 GB DDR3 1.6Ghz (800 MHz Dual Channel)
OS: Windows 7 Home Premium x64

Sorry for being unable to give any more information. Any ideas or stuff I forgot to include?

**Comment by DanielGibson** [comment]
if you really want ugly particles, use the GL3 renderer and `gl3_particle_square 1`

**Comment by Yamagi** [comment]
We've fixed the particle rendering in GL1 with b7bf822e6d985c1fe1c88ae3355ea646f5561e4e. As @DanielGibson said, if you really want broken / ugly particles use GL3.

**Comment by drogga** [comment]
Playing the latest stable 7.41 amd the CVar still doesn't work for me?
Anything I'm doing wrong?

**Comment by DanielGibson** [comment]
are you using the GL3 renderer?
as the name suggests, "gl3_particle_square 1" only works with it
