### ISSUE TITLE
[Bug] Repair Bot stuck and do nothing after exit game and loading save in The Reckocning addon.

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#485]
In The Reckocning addon, if there is  Repair Bot (small flying enemy that resurrects stroggs) on a map and you not trigger him, then save game, exit and launch game again and load this save, and go to Repair Bot, it will stuck and do nothig untill you shoot him. But if map loads in one session of the game, Repair Bot will fly and ressurect stroggs. It can be seen in map xcompnd1.bsp. My system is Windows 10 x64.  Thank you!

**Comment by Yamagi** [comment]
This might be already fixed in HEAD, since we had some bugfixes for the fixbot. The bigger plan is to fix #484 and publish a release candidate for 7.42 after that. It shouldn't take too long and I'll report back as soon as I have binaries to test.

**Comment by Yamagi** [comment]
An up to set of Windows binaries - hopefully more or less the same as the upcomming 7.42 release - can be found here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20191117-fbf103b-7.42-RC1.zip

**Comment by StepanST** [comment]
Hi, just tried 7.42 version, bug still exist. Just keep in touch)

**Comment by BjossiAlfreds** [comment]
Just wondering, were you playing in original 7.41 release when you first experienced this? I'll look into this and see if I can find out what is going on.

**Comment by StepanST** [comment]
I first see thith on map  xcompnd1.bsp. This on on screenshot is stack 
![q2_0000](https://user-images.githubusercontent.com/43229017/72385594-72bc2400-3752-11ea-8bd5-ae8a24922d56.png)

To see this load map in the begining, save, exit game and than lounch it again and load save - Repair Bot will stack. 

I tried noclip cheat and saw than Repair Bot is not spawn on map at start, like others. It spawns when you walk on some area. Maybe problem is with it? Like another enemes spawn right after begining of level, so they save and load correctly, but Repair Bot spawns after that, so some information dont saves correctly and lost after exit game?

**Comment by BjossiAlfreds** [comment]
xcmpnd1 has one fixbot with spawnflags 4 (roam), and several with spawnflags 6 (roam + triggered spawn) and one with spawnflags 774 (hard mode only + roam + triggered spawn). All the triggered spawn ones have targetname t148. The issue may be more complicated than just the triggered spawn behavior if not all of the triggered spawn guys get stuck.

I will attempt to reproduce this on my side. If I can do that I'll try to figure out what is happening with their AI.

**Comment by BjossiAlfreds** [comment]
I was able to reproduce it and I figured out what is going on: The bots are getting stuck trying to reach their object_repair goal entities, which are level entities that function as welding targets for the fixbots.

The problem is actually two-fold:
1. Xatrix forgot to call gi.linkentity() when the object_repair entities are spawned on level start, which means they will not collide with other entities even if the bboxes intersect, and also means the object_repair's absmin and absmax points are set to 0,0,0. However, loading savegames will always call gi.linkentity() on all loaded entities, causing the object_repair entities to collide correctly and have correct absmin and absmax.

Fixing this is easy enough - change solidity to SOLID_TRIGGER so that the bboxes can intersect (would be annoying if players would bump into tiny invisible boxes), and call gi.linkentity() in the spawn function. This will create a consistent state between savegame loads, but introduces a new problem.

2. When the object_repair entities are correctly linked to the collision detection system through gi.linkentity(), it causes reachability to object_repair to become error-prone. When absmin and absmax were 0,0,0 before loading the savegame, it meant that CloseEnough() in m_move.c would be very optimistic and let the fixbots get very close to the object_repair entities, but when absmin and absmax are correctly set, CloseEnough() will start returning true earlier and so the fixbots will get stuck trying to get close enough to their object_repair goal.

As with several other things, Xatrix broken code works "by accident" before a savegame load, but breaks after that.

Overall I think 3 things need to be done to fix this:
* object_repair solidity and call gi.linkentity() for consistent results across savegame loads
* Make it easier for the fixbots to reach object_repair, for example by increasing the minimum length (currently it is 32 which is very small given the bbox sizes involved)
* Add AI logic that makes fixbots give up after a while if they do get stuck

@Yamagi, any thoughts on this?

**Comment by StepanST** [comment]
Thank you very match for your work! Think this port is the best for playing Quake 2. It would be better if i have game.dll to test:)

**Comment by BjossiAlfreds** [comment]
Here is a 32-bit game.dll, should work with the pre-build Windows binaries from the Yamagi Q2 website:

[fixbot-stuck.zip](https://github.com/yquake2/yquake2/files/4065017/fixbot-stuck.zip)

**Comment by StepanST** [comment]
Looks like everything fine:) Will this be a part of next release?

**Comment by Yamagi** [comment]
The fixbots never did anything useful. They were just there, floating around, spawning some particles and zapping very slow and stupid players. ;) So keeping the pathfinding stuff like it is should be okay, it'll never become a serious enemy. 

I like the approach. It fixes the bug and isn't too invasive. @BjossiAlfreds, can you open a pull request? I'll merge it. I can provide a new set of binaries tonight.

**Comment by BjossiAlfreds** [comment]
Xatrix had much bigger plans for the fixbots judging by all the unused moves and code. object_repair entities will fire their target when a fixbot fixes them the first time, could have been an interesting gameplay mechanic but was never used as far as I know.

**Comment by Yamagi** [comment]
A new build with YQ2 and all 3 official addons updated is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20200115-29d607c.zip

@BjossiAlfreds: Thank you for investigating and fixing this!

**Comment by BjossiAlfreds** [comment]
No problem! Took 3 revisions but got to a pretty good result in the end.
