### ISSUE TITLE
[Bug] Maps with special chars in cmd line

### ISSUE THREAD

**Issue by NightFright2k19** [yquake2/yquake2#757]
Yamagi 8.0 apparently cannot properly load maps with special chars in it during startup via command line (not ingame).

Example: Scorched Earth
Map name (e.g.): SGC9-1.bsp

When trying to load the mod with 
**yquake2.exe +set game scorched +set skill 0 +map sgc9-1**
you get an error ("Can't find maps/sgc9.bsp"). This means the "-1" part of the map name is not parsed. Same with "-2", "-3" etc. It works if you rename the file, e.g. to sgc9_1.bsp.

Maps load without issue when launched via ingame console (map sgc9-1).

At first I thought this was an issue with my launcher (Simple Quake Launcher 2.5), but [the SQL author checked it](https://github.com/m-x-d/Simple-Quake-Launcher-2/issues/9) and says it must be port-related.

**Comment by maraakate** [comment]
If I remember correctly, Cbuf_AddLateCommands is for some bologna with setting CVARs at the right time during Qcommon_Init() which may not be initialized until after the CVAR_Init(), Server_Init(), etc. friends are done.  So it basically adds it twice.  However, it's been a long time since I've goofed with it and may be wrong.

**Comment by DanielGibson** [comment]
I just pushed a minimal fix for this

**Comment by NightFright2k19** [comment]
I can confirm this works now.

**Comment by NightFright2k19** [comment]
It seems Yamagi still cannot load some maps with special chars, at least not when they are at the end of the map name. There is a DM map named _wtf!.bsp_ and only loads if you put something after the exclamation mark, e.g. _wtf!**1**.bsp_.

**Comment by NightFright2k19** [comment]
Probably a mistake from my side. I had these maps in the mapcycle list of the Eraser bot (maps.txt) and when they wouldn't load, I assumed it was port-related. Anyway, Eraser game code is from 1998 and I guess it has something to do with that.
